library('RSQLite')
library('ggplot2')
setwd("~/Desktop/github/data_sci/project")
sqlite <- dbDriver("SQLite")
companiesdb <- dbConnect(sqlite,"companies.db")
dbListTables(companiesdb)
dbListFields(companiesdb,"companies")
results<-dbGetQuery(companiesdb,"SELECT name, categorycode from companies where categorycode is not null")
c <- ggplot(results, aes(categorycode))
c + geom_bar()
