library('RSQLite')
setwd("~/Desktop/data_sci/crunchbase")
sqlite <- dbDriver("SQLite")
healthcaredb <- dbConnect(sqlite,"healthcare.db")
dbListTables(healthcaredb)
dbListFields(healthcaredb,"recs")
dbGetQuery(healthcaredb,"SELECT namespace, count(name) from recs group by namespace")
results2<-dbGetQuery(healthcaredb,"SELECT namespace, name from recs")
c <- ggplot(results2, aes(namespace))
c + geom_bar()